---
- name: "Deploy ApacheDS"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_method: "ansible.builtin.sudo"

  tasks:
    - name: "Install ApacheDS"
      when: inv_install_apacheds | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          vars:
            prepare_host__system_users: "{{ inv_prepare_host__apacheds_system_users }}"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.install_java"
          tags:
            - "labocbz.install_java"
          vars:
            install_java__version: "{{ inv_install_java__version }}"
            install_java__cpu_architecture: "{{ inv_install_java__cpu_architecture }}"
            install_java__version_is_default: true
          ansible.builtin.include_role:
            name: "labocbz.install_java"

        - name: "Include labocbz.add_certificates"
          tags:
            - "labocbz.add_certificates"
          loop: "{{ inv_apacheds_cert_bundles }}"
          loop_control:
            loop_var: bundle
          when: inv_apacheds_cert_bundles is defined
          vars:
            add_certificates__bundle_name: "{{ bundle.name }}"
            add_certificates__bundle_type: "{{ bundle.type }}"
            add_certificates__bundle_src: "{{ bundle.src }}"
            add_certificates__bundle_dest: "{{ bundle.dest }}"
            add_certificates__bundle_src_user: "{{ bundle.src_user }}"
            add_certificates__bundle_src_password: "{{ bundle.src_password }}"
            add_certificates__bundle_dest_user: "{{ bundle.dest_user }}"
            add_certificates__bundle_dest_group: "{{ bundle.dest_group }}"
            add_certificates__bundle_dest_mode: "{{ bundle.dest_mode }}"
          ansible.builtin.include_role:
            name: "labocbz.add_certificates"

        - name: "Include labocbz.install_apacheds"
          tags:
            - "labocbz.install_apacheds"
          vars:
            install_apacheds__version: "{{ inv_install_apacheds__version }}"
            install_apacheds__user: "{{ inv_install_apacheds__user }}"
            install_apacheds__group: "{{ inv_install_apacheds__group }}"
            install_apacheds__install_dir: "{{ inv_install_apacheds__install_dir }}"
            install_apacheds__path: "{{ inv_install_apacheds__path }}"
            install_apacheds__instances: "{{ inv_install_apacheds__instances }}"
            install_apacheds__ssl_path: "{{ inv_install_apacheds__ssl_path }}"
            install_apacheds__ssl_ca: "{{ inv_install_apacheds__ssl_ca }}"
            install_apacheds__ssl: "{{ inv_install_apacheds__ssl }}"
            install_apacheds__ssl_crt: "{{ inv_install_apacheds__ssl_crt }}"
            install_apacheds__ssl_key: "{{ inv_install_apacheds__ssl_key }}"
            install_apacheds__ssl_p12_password: "{{ inv_install_apacheds__ssl_p12_password }}"
          ansible.builtin.include_role:
            name: "labocbz.install_apacheds"
